import os
from google import genai
from dotenv import load_dotenv
import logging

# Set up logging
logger = logging.getLogger(__name__)

# Load environment variables (if not already loaded globally, e.g., in main.py)
# If main.py already loads it, this line can be removed.
load_dotenv()

# Configure the Gemini client
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY not found in environment variables. Please set it in your .env file.")

# Use genai.Client as per the original reference and error message implication
client = genai.Client(api_key=api_key)

def generate_chat_response(user_prompt: str) -> str:
    """
    Generates a response from the Gemini model based on the user prompt,
    handling streaming internally using genai.Client and returning the complete response.

    Args:
        user_prompt: The input text from the user.

    Returns:
        The complete text response generated by the model.
    """
    full_response = ""
    try:
        # Use the client to generate content stream
        # Note: Adjust model name if 'gemini-2.0-flash' is not correct or available
        # The 'contents' format might need specific structuring depending on the API version
        # Using a simple list with the user prompt for now.
        response_stream = client.models.generate_content_stream(
            model="gemini-1.5-flash", # Using flash as a generally available model
            contents=[user_prompt] # Pass the prompt in the expected list format
        )

        for chunk in response_stream:
            # Append text from chunk, checking if text exists
            # Need to verify the exact structure of the chunk from client.models.generate_content_stream
            if hasattr(chunk, 'text') and chunk.text:
                 full_response += chunk.text
            else:
                 # Log if a chunk doesn't contain text (e.g., safety feedback or different structure)
                 logger.warning(f"Received a chunk without text or with empty text: {chunk}")

        # Add safety feedback check if available in this client's response structure
        # This part is speculative without knowing the exact response object details
        # if not full_response and hasattr(response_stream, 'prompt_feedback') and response_stream.prompt_feedback:
        #     return f"Error: Prompt blocked due to {response_stream.prompt_feedback.block_reason}. Please modify your prompt."

        return full_response

    except Exception as e:
        logger.error(f"Error during Gemini API stream: {e}", exc_info=True)
        # Provide a generic error message to the user
        return "Error: Failed to get response from the language model."

# Example usage (optional, for testing)
# if __name__ == '__main__':
#    test_prompt = "Explain the concept of streaming in APIs."
#    print(f"Prompt: {test_prompt}")
#    print(f"Response:\n{generate_chat_response(test_prompt)}")
